---
- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: OpenJDK | Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ jdk_packages }}"
  when: "{{ jdk_packages }}"

